### ISSUE TITLE
Sender is always rewritten

### ISSUE THREAD

**Issue by Carbenium** [uubk/mailclient#2]
Sender is rewritten even if mailclient_sender/domain is False leading to something like ```False@domain.com```

**Comment by uubk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offene PRs](https://trello.com/c/ZKCMhV9y/93-offene-prs)

**Comment by uubk** [comment]
Hmm, originally this was not intended to be used as a ordinary mail relay. I'll add a workaround for you.

**Comment by uubk** [comment]
Can you try the `no-sender-rewrite` branch and see whether that works for you?

**Comment by Carbenium** [comment]
Code looks okay to me. In my opinion it would also suffice to just bail out if no valid value for the setting is given.

**Comment by uubk** [comment]
merged.
